name: Build and Send APKs

on:
  push:
    branches:
      - develop  # Укажите ветку, на которую нужно реагировать

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Extract version information
      id: version
      run: |
        VERSION_NAME=$(grep -oP 'versionName "\K[^"]+' app/build.gradle)
        VERSION_CODE=$(grep -oP 'versionCode \K\d+' app/build.gradle)
        echo "Version Name: $VERSION_NAME"
        echo "Version Code: $VERSION_CODE"
        echo "::set-output name=version_name::$VERSION_NAME"
        echo "::set-output name=version_code::$VERSION_CODE"

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

  send-to-telegram:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Release APK
      uses: actions/download-artifact@v3
      with:
        name: app-release
        path: ./apk

    - name: Download Debug APK
      uses: actions/download-artifact@v3
      with:
        name: app-debug
        path: ./apk

    - name: Send APKs to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        files: |
          ./apk/app-release.apk
          ./apk/app-debug.apk
        caption: "Новые сборки APK доступны! Версия: ${{ steps.version.outputs.version_name }} (Code: ${{ steps.version.outputs.version_code }})"
